import { v4 as uuidv4 } from 'uuid';
import { Task, Project } from './types';

const now = new Date().toISOString();
const yesterday = new Date(Date.now() - 86400000).toISOString();
const twoDaysAgo = new Date(Date.now() - 172800000).toISOString();
const threeDaysAgo = new Date(Date.now() - 259200000).toISOString();
const nextWeek = new Date(Date.now() + 604800000).toISOString().split('T')[0];
const tomorrow = new Date(Date.now() + 86400000).toISOString().split('T')[0];
const in3Days = new Date(Date.now() + 259200000).toISOString().split('T')[0];

export const seedProjects: Project[] = [
  {
    id: 'proj-1',
    name: 'Website Redesign',
    description: 'Complete overhaul of the company website with new branding, improved UX, and mobile-first approach.',
    color: '#6366f1',
    createdAt: threeDaysAgo,
    archived: false,
  },
  {
    id: 'proj-2',
    name: 'Q2 Marketing Campaign',
    description: 'Plan and execute the Q2 marketing push including social media, email sequences, and landing pages.',
    color: '#f59e0b',
    createdAt: twoDaysAgo,
    archived: false,
  },
  {
    id: 'proj-3',
    name: 'Home Office Setup',
    description: 'Create a productive and ergonomic home office workspace.',
    color: '#10b981',
    createdAt: yesterday,
    archived: false,
  },
  {
    id: 'proj-4',
    name: 'Learn Rust',
    description: 'Complete the Rust programming book and build a small CLI tool.',
    color: '#ef4444',
    createdAt: threeDaysAgo,
    archived: false,
  },
];

export const seedTasks: Task[] = [
  // Inbox items
  {
    id: uuidv4(),
    title: 'Check if the new API rate limits affect our integration',
    notes: 'Saw a tweet about Stripe changing their rate limits. Need to verify.',
    status: 'inbox',
    projectId: null,
    context: '@computer',
    timeEstimate: '10m',
    energyLevel: 'low',
    dueDate: null,
    delegatedTo: null,
    createdAt: now,
    completedAt: null,
    order: 0,
  },
  {
    id: uuidv4(),
    title: 'Research standing desk options',
    notes: 'Uplift V2 vs Autonomous SmartDesk. Budget: $500-800',
    status: 'inbox',
    projectId: 'proj-3',
    context: '@computer',
    timeEstimate: '30m',
    energyLevel: 'low',
    dueDate: null,
    delegatedTo: null,
    createdAt: now,
    completedAt: null,
    order: 1,
  },
  {
    id: uuidv4(),
    title: 'Idea: Build a habit tracking app',
    notes: 'Minimalist habit tracker with streaks and weekly reviews.',
    status: 'inbox',
    projectId: null,
    context: null,
    timeEstimate: null,
    energyLevel: null,
    dueDate: null,
    delegatedTo: null,
    createdAt: now,
    completedAt: null,
    order: 2,
  },
  // Next Actions
  {
    id: uuidv4(),
    title: 'Review and approve homepage mockups',
    notes: 'Sarah sent the final mockups via Figma. Check mobile breakpoints.',
    status: 'next_action',
    projectId: 'proj-1',
    context: '@computer',
    timeEstimate: '30m',
    energyLevel: 'high',
    dueDate: tomorrow,
    delegatedTo: null,
    createdAt: twoDaysAgo,
    completedAt: null,
    order: 0,
  },
  {
    id: uuidv4(),
    title: 'Write email sequence for product launch',
    notes: '5-email sequence: announcement, features, testimonials, urgency, last chance.',
    status: 'next_action',
    projectId: 'proj-2',
    context: '@computer',
    timeEstimate: '30m',
    energyLevel: 'high',
    dueDate: nextWeek,
    delegatedTo: null,
    createdAt: yesterday,
    completedAt: null,
    order: 1,
  },
  {
    id: uuidv4(),
    title: 'Call electrician about office wiring',
    notes: 'Need additional outlets for the new desk setup.',
    status: 'next_action',
    projectId: 'proj-3',
    context: '@phone',
    timeEstimate: '5m',
    energyLevel: 'low',
    dueDate: null,
    delegatedTo: null,
    createdAt: yesterday,
    completedAt: null,
    order: 2,
  },
  {
    id: uuidv4(),
    title: 'Order ergonomic keyboard',
    notes: 'Kinesis Advantage 360 or ZSA Moonlander.',
    status: 'next_action',
    projectId: 'proj-3',
    context: '@computer',
    timeEstimate: '10m',
    energyLevel: 'low',
    dueDate: null,
    delegatedTo: null,
    createdAt: yesterday,
    completedAt: null,
    order: 3,
  },
  {
    id: uuidv4(),
    title: 'Complete Rust chapter 10: Generic Types',
    notes: 'Focus on lifetimes and trait bounds.',
    status: 'next_action',
    projectId: 'proj-4',
    context: '@computer',
    timeEstimate: '30m',
    energyLevel: 'high',
    dueDate: null,
    delegatedTo: null,
    createdAt: threeDaysAgo,
    completedAt: null,
    order: 4,
  },
  {
    id: uuidv4(),
    title: 'Drop off dry cleaning',
    notes: '',
    status: 'next_action',
    projectId: null,
    context: '@errands',
    timeEstimate: '10m',
    energyLevel: 'low',
    dueDate: tomorrow,
    delegatedTo: null,
    createdAt: twoDaysAgo,
    completedAt: null,
    order: 5,
  },
  {
    id: uuidv4(),
    title: 'Fix broken link on pricing page',
    notes: 'The "Enterprise" link goes to 404. Check routing config.',
    status: 'next_action',
    projectId: 'proj-1',
    context: '@work',
    timeEstimate: '5m',
    energyLevel: 'low',
    dueDate: yesterday.split('T')[0],
    delegatedTo: null,
    createdAt: twoDaysAgo,
    completedAt: null,
    order: 6,
  },
  // Waiting For
  {
    id: uuidv4(),
    title: 'Logo concepts from design team',
    notes: 'Expected by end of week. Brief was sent Monday.',
    status: 'waiting_for',
    projectId: 'proj-1',
    context: null,
    timeEstimate: null,
    energyLevel: null,
    dueDate: in3Days,
    delegatedTo: 'Sarah (Design Lead)',
    createdAt: twoDaysAgo,
    completedAt: null,
    order: 0,
  },
  {
    id: uuidv4(),
    title: 'Vendor quote for standing desk',
    notes: 'Requested quote from 3 vendors. Waiting for response.',
    status: 'waiting_for',
    projectId: 'proj-3',
    context: null,
    timeEstimate: null,
    energyLevel: null,
    dueDate: nextWeek,
    delegatedTo: 'Office Supplies Co.',
    createdAt: yesterday,
    completedAt: null,
    order: 1,
  },
  {
    id: uuidv4(),
    title: 'Approval from legal on ad copy',
    notes: 'Sent compliance review request Tuesday.',
    status: 'waiting_for',
    projectId: 'proj-2',
    context: null,
    timeEstimate: null,
    energyLevel: null,
    dueDate: in3Days,
    delegatedTo: 'Mike (Legal)',
    createdAt: twoDaysAgo,
    completedAt: null,
    order: 2,
  },
  // Someday/Maybe
  {
    id: uuidv4(),
    title: 'Learn to play piano',
    notes: 'Find a good online course. Maybe Piano Marvel or Flowkey.',
    status: 'someday_maybe',
    projectId: null,
    context: '@home',
    timeEstimate: null,
    energyLevel: null,
    dueDate: null,
    delegatedTo: null,
    createdAt: threeDaysAgo,
    completedAt: null,
    order: 0,
  },
  {
    id: uuidv4(),
    title: 'Start a tech blog',
    notes: 'Write about software architecture and developer experience.',
    status: 'someday_maybe',
    projectId: null,
    context: '@computer',
    timeEstimate: null,
    energyLevel: null,
    dueDate: null,
    delegatedTo: null,
    createdAt: threeDaysAgo,
    completedAt: null,
    order: 1,
  },
  {
    id: uuidv4(),
    title: 'Plan trip to Japan',
    notes: 'Cherry blossom season. 2 weeks. Kyoto, Tokyo, Osaka.',
    status: 'someday_maybe',
    projectId: null,
    context: '@computer',
    timeEstimate: null,
    energyLevel: null,
    dueDate: null,
    delegatedTo: null,
    createdAt: threeDaysAgo,
    completedAt: null,
    order: 2,
  },
  {
    id: uuidv4(),
    title: 'Contribute to open source project',
    notes: 'Maybe help with the Rust compiler or a tool I use daily.',
    status: 'someday_maybe',
    projectId: 'proj-4',
    context: '@computer',
    timeEstimate: null,
    energyLevel: null,
    dueDate: null,
    delegatedTo: null,
    createdAt: threeDaysAgo,
    completedAt: null,
    order: 3,
  },
  // Completed
  {
    id: uuidv4(),
    title: 'Set up project repository',
    notes: 'Created monorepo with Turborepo. CI/CD configured.',
    status: 'completed',
    projectId: 'proj-1',
    context: '@computer',
    timeEstimate: '30m',
    energyLevel: 'high',
    dueDate: null,
    delegatedTo: null,
    createdAt: threeDaysAgo,
    completedAt: yesterday,
    order: 0,
  },
  {
    id: uuidv4(),
    title: 'Define brand color palette',
    notes: 'Primary: Indigo, Secondary: Amber, Neutral: Slate.',
    status: 'completed',
    projectId: 'proj-1',
    context: '@work',
    timeEstimate: '10m',
    energyLevel: 'low',
    dueDate: null,
    delegatedTo: null,
    createdAt: threeDaysAgo,
    completedAt: twoDaysAgo,
    order: 1,
  },
];
